// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using se4458_midterm.Context;

#nullable disable

namespace se4458_midterm.Migrations
{
    [DbContext(typeof(AirlineDbContext))]
    [Migration("20231125150824_ChangeUserSQLDB")]
    partial class ChangeUserSQLDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("se4458_midterm.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 50,
                            Capacity = 100,
                            Departure = "Boston",
                            DepartureDate = new DateTime(2023, 6, 1, 7, 40, 0, 0, DateTimeKind.Unspecified),
                            Destination = "New York",
                            FlightNumber = 4428,
                            Price = 50.0
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 4,
                            Capacity = 200,
                            Departure = "Berlin",
                            DepartureDate = new DateTime(2023, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Istanbul",
                            FlightNumber = 5626,
                            Price = 60.0
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 5,
                            Capacity = 100,
                            Departure = "Berlin",
                            DepartureDate = new DateTime(2023, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Istanbul",
                            FlightNumber = 6550,
                            Price = 50.0
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 50,
                            Capacity = 100,
                            Departure = "Boston",
                            DepartureDate = new DateTime(2023, 6, 1, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            Destination = "New York",
                            FlightNumber = 3328,
                            Price = 40.0
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 50,
                            Capacity = 100,
                            Departure = "Tokyo",
                            DepartureDate = new DateTime(2023, 10, 2, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Toronto",
                            FlightNumber = 2233,
                            Price = 140.0
                        });
                });

            modelBuilder.Entity("se4458_midterm.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin",
                            Password = "admin",
                            Role = "admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "passenger",
                            Password = "12345",
                            Role = "passenger",
                            UserName = "se4458_passenger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
